# Generated by Django 5.0.6 on 2024-06-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='message_img/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='message_vid/'),
        ),
    ]
