# Generated by Django 5.0.6 on 2024-06-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_remove_advertising_delete_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='delete_timer',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
