# Generated by Django 5.0.6 on 2024-06-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_advertising_delete_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tg_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
